title: Andres Bermeo Blog
author: Andres Bermeo
email: your-email@domain.com
description: I'm backend developer, especially in Java and Python technologies, I love the open source and Linux.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
